FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Services/Posts/Posts.API/Posts.API.csproj", "Services/Posts/Posts.API/"]
COPY ["Services/Posts/Posts.Infrastructure/Posts.Infrastructure.csproj", "Services/Posts/Posts.Infrastructure/"]
COPY ["Services/Posts/Posts.Domain/Posts.Domain.csproj", "Services/Posts/Posts.Domain/"]
COPY ["Services/Bloggest.Common/Bloggest.Common.csproj", "Services/Bloggest.Common/"]
COPY ["Services/Posts/Posts.Application/Posts.Application.csproj", "Services/Posts/Posts.Application/"]
RUN dotnet restore "Services/Posts/Posts.API/Posts.API.csproj"
COPY . .
WORKDIR "/src/Services/Posts/Posts.API"
RUN dotnet build "Posts.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Posts.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Posts.API.dll"]
