name: tests

on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Install dependencies
        run: dotnet restore src
      - name: Build
        run: dotnet build src
      - name: Запуск unit tests для сборки Posts.UnitTests
        run: dotnet test ./src/Services/Posts/Posts.UnitTests/Posts.UnitTests.csproj